#!/bin/sh

function help () {
  echo "### Git Staging Tool ###";
  echo "Usage: gst <command> <search>";
  echo " - Find file names from git status including <search> and execute git command <command> with them";
  echo " - Supported commands: git add, git unstage, git rm"; # XXX try checkout --
  echo "";
}

# TODO:
# - select command intelligently based on staged / unstaged
# - feedback to stdout wether "added", "not found" etc

if [ -z "$2" ]
then
  command="add";
  search=$1;
else
  command=$1;
  search=$2;
fi

if [ -n "$search" ]
then
    files=`git status -s | sed 's/^ *//' | tr -s " " | cut -d " " -f 2`
    #echo $files # debug
    for f in $files
    do
      match=`echo $f | grep -i $search`;
      if [ -n "$match" ]
      then
        #echo "File found: search=$search"; # debug
        git $command $match;
      #else
        #echo "File not found: search=$search"; # debug
      fi
    done
else
    help
fi

git status